Add style.css and index.html
AACHOURMOHAMED/code-review pull request #1
Opened 2022-05-31 08:42 UTC by AACHOURMOHAMED

Add style.css and index.html

2022-05-31 08:54 UTC, AACHOURMOHAMED reviewed
# Changes required ♻
[https://c.tenor.com/isiLRnxz3zwAAAAC/cat-driving-serious.gif](url)
Well done on a job done so far, however, there are a few changes required for you to get to the next phase of the project. Thanks.

2022-05-31 08:54 UTC, AACHOURMOHAMED commented on index.html
> +            </P>
kindly use tag h1 only one time for best practices HTML 
check this link  [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-05-31 09:20 UTC, ishimwezachee requested changes
Hi @AACHOURMOHAMED   , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 

## Required Changes ♻️

- [ ] Could you review your Reame.md documentation. It is not professional

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Ishimwe Zachee  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-05-31 09:20 UTC, ishimwezachee commented on index.html
> +
- [OPTIOANAL ] You should review the spaces through your codes. Kindly review these space, and explain to students why its important to not add spaces in codes

2022-05-31 09:40 UTC, AACHOURMOHAMED reviewed
# require changes  :recycle:

## Hi [@AACHOURMOHAMED ](https://github.com/ )👋


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![2DrZ](https://user-images.githubusercontent.com/92208712/196364621-fffadf24-c62d-4e23-a65f-9bb10efb3b9e.gif)



## Highlights 🌟

- ✔️ Descriptive commmit messsages
- :x:  Descriptive PR description
-  :x: No linter Errors

# require changes  :recycle:

- [ ] kindly Add a description to the Readme file please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.



Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@AACHOURMOHAMED](https://img.shields.io/github/followers/AACHOURMOHAMED?label=Ashour&style=social)](https://github.com/AACHOURMOHAMED)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 09:40 UTC, AACHOURMOHAMED commented on index.html
> +
[OPTIONAL ] kindly remove the space between your code to keep your work clean (clean code) Thanks

2022-05-31 09:46 UTC, ishimwezachee approved these changes
Hi @AACHOURMOHAMED , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/d00XhVJERxCdW/giphy.gif"/>
## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 09:49 UTC, merged

2022-10-18 11:11 UTC, AACHOURMOHAMED commented
Thank you for approving the code review